config/routes.rb
Rails.application.routes.draw do
  root 'profile#index'

  devise_for :users

  resources :profile, only: [:index, :edit, :update]

  resources :transactions, only: [:index, :new, :create]

  resources :users, only: [:index, :edit, :update] do
    resources :invites, only: [:create, :index, :update]
  end

  resources :friends, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invite.rb
class Invite < ApplicationRecord
  enum status: { pending: 0, accepted: 1, denied: 2 }

  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :sender, :receiver, :status, presence: true
  validates :sender, uniqueness: { scope: :receiver }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :amount, :sender, :receiver, presence: true

  validate :if_enough_funds?

  private

  def if_enough_funds?
    return if sender.nil?
    self.errors.add(:no_funds, 'Balance to low') if sender.current_balance < (amount || 0)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :outgoing_transactions, class_name: 'Transaction', foreign_key: :sender_id, dependent: :restrict_with_error
  has_many :incoming_transactions, class_name: 'Transaction', foreign_key: :receiver_id, dependent: :restrict_with_error

  has_many :outgoing_friend_invites, class_name: 'Invite', foreign_key: :sender_id, dependent: :destroy
  has_many :incoming_friend_invites, class_name: 'Invite', foreign_key: :receiver_id, dependent: :destroy

  has_many :accepted_outgoing_friend_invites, -> { where(status: :accepted)}, class_name: 'Invite', foreign_key: :sender_id
  has_many :accepted_incoming_friend_invites, -> { where(status: :accepted)}, class_name: 'Invite', foreign_key: :receiver_id

  has_many :friends_invited_by_me, through: :accepted_outgoing_friend_invites, source: :receiver, class_name: 'User'
  has_many :friends_who_invited_me, through: :accepted_incoming_friend_invites, source: :sender, class_name: 'User'

  def all_friends
    (friends_invited_by_me + friends_who_invited_me).uniq
  end

  def all_transactions
    Transaction
      .where("sender_id = :id OR receiver_id = :id", id: self.id)
      .includes(:sender, :receiver)
      .order(created_at: :desc)
  end

  def invite_sent?(friend_id)
    Invite
      .where("
        sender_id = :friend_id AND receiver_id = :id
        OR
        sender_id = :id AND receiver_id = :friend_id", friend_id: friend_id, id: self.id).present?

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends =
      current_user
      .all_friends
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def index
    @pending_invites =
      current_user
      .incoming_friend_invites
      .pending
      .includes(:sender)
      .page(params[:page])
  end

  def create
    @invite = current_user.outgoing_friend_invites.new(receiver_id: params[:user_id])
    if @invite.save
      redirect_to users_path, notice: "Friend request is sent!"
    else
      redirect_to users_path, flash: { error: @invite.errors.full_messages }
    end
  end

  def update
    @invite = current_user.incoming_friend_invites.find(params[:id])
    if @invite.update(status: params[:status])
      redirect_to user_invites_path(current_user), notice: "Friend #{params[:status]}!"
    else
      redirect_to user_invites_path(current_user), flash: { error: @invite.errors.full_messages }
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end

  def edit
  end

  def update
    if current_user.update(permitted_params)
      redirect_to profile_index_path(current_user), notice: "Initial balance added!"
    else
      redirect_to edit_profile_path(current_user), flash: { error: current_user.errors.full_messages }
    end
  end

  private

  def permitted_params
    params.require(:user).permit(:current_balance)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions =
      current_user
      .all_transactions
      .page(params[:page])
  end

  def new
    @transaction = Transaction.new
  end

  def create
    transaction_creator = TransactionCreator.new(current_user, permitted_params)
    @transaction = transaction_creator.call
    if @transaction.persisted?
      redirect_to transactions_path, notice: "Transaction sucessfully created!"
    else
      flash[:error] = @transaction.errors.full_messages
      render :new
    end
  end

  private

  def permitted_params
    params.require(:transaction).permit(:receiver_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users =
      User
      .all
      .where.not(id: current_user)
      .page(params[:page])
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_datetime(datetime)
    datetime.strftime("%d/%m/%Y %H:%M")
  end

  def alert_class(type)
    case type
      when :alert then :error
      when :notice then :info
      when :error then :danger
      else type
    end
  end
end

app/views/friends/index.slim
.box.col-md-12
  .box-header
    h2 All friends
  .box-content

    table.table.table-striped.table-bordered
      thead
        th Email
        th
      tbody
        - @friends.each do |friend|
          tr
            td= friend.email

app/views/invites/index.slim
.box.col-md-12
  .box-header
    h2 Pending invites
  .box-content

    table.table.table-striped.table-bordered
      thead
        th Email
        th
      tbody
        - @pending_invites.each do |invite|
          tr
            td= invite.sender.email
            td= link_to 'Accept friend', user_invite_path(current_user, invite, status: :accepted), method: :put, class: 'btn btn-primary'
            td= link_to 'Deny friend', user_invite_path(current_user, invite, status: :denied), method: :put, class: 'btn btn-warning'
      = paginate(@pending_invites)

app/views/layouts/_nav.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand href="#" Navbar
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    ul.navbar-nav
      li.nav-item
        = link_to 'My profile', profile_index_path, class: 'nav-link'
      li.nav-item
        = link_to 'Transactions', transactions_path, class: 'nav-link'
      li.nav-item
        = link_to 'Users', users_path, class: 'nav-link'
      li.nav-item
        = link_to 'Friends', friends_path, class: 'nav-link'
      li.nav-item
        = link_to 'Pending invites', user_invites_path(current_user), class: 'nav-link'
      li.nav-item
        = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link'

app/views/layouts/application.slim
doctype html
html
  head
    title SimpleBillingWebApp
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    - if user_signed_in?
      = render 'layouts/nav'
    - flash.each do |key, value|
      p class="alert alert-#{alert_class(key.to_sym)}" = value

    = yield

app/views/transactions/index.slim
.box.col-md-12
  .box-header
    h2 My transactions
  .box-content
    br
    = link_to 'New transaction', new_transaction_path, class: "btn btn-primary"

    br
    table.table.table-striped.table-bordered
      thead
        th Sender
        th Receiver
        th Amount
        th My balance
        th Date
      tbody
        - @transactions.each do |transaction|
          tr
            td= transaction.sender.email
            td= transaction.receiver.email
            td= transaction.amount
            td= (current_user == transaction.sender) ? transaction.sender_balance : transaction.receiver_balance
            td= format_datetime(transaction.created_at)
      = paginate(@transactions)

app/views/transactions/new.slim
.box.col-md-12
  .box-header
    h2 New Transaction
  .box-content
    = simple_form_for @transaction, html: { novalidate: false } do |f|
      = f.association :receiver, collection: User.all.where("id != ?", current_user.id), label_method: :email, value_method: :id, prompt: 'Select receiver', required: true
      = f.input :amount, required: true

      .form-actions
        = f.button :submit, class: 'btn-primary', data: { disable_with: 'Transaction in progress...' }

app/views/users/index.slim
.box.col-md-12
  .box-header
    h2 All users
  .box-content

    table.table.table-striped.table-bordered
      thead
        th Email
        th
      tbody
        - @users.each do |user|
          tr
            td= user.email
            - unless current_user.invite_sent?(user.id)
              td= link_to 'Add friend', user_invites_path(user), method: :post, class: 'btn btn-primary'
            - else
              td= link_to 'Invite sent', '', class: 'btn btn-success'
      = paginate(@users)